Removed rest-client, use net/http instead
jeroenj/geo_ip pull request #20
Opened 2018-03-01 10:00 UTC by elfenars

What the title says.

2018-03-02 16:06 UTC, jeroenj requested changes
Thanks a lot for this! This finally drops all dependencies for this gem and bumps the specs to RSpec 3. 👌 

I'll release an updated version once the feedback has been checkend and the PR has been merged. 👍

2018-03-02 16:06 UTC, jeroenj commented on geo_ip.gemspec
> +  s.add_development_dependency 'rspec'
Could you lock this to `~> 3.0`? Since a major release might break stuff. :)

2018-03-02 16:06 UTC, jeroenj commented on spec/geo_ip_spec.rb
> +      expect(geolocation[:timezone]).to eq('-08:00') # This one is likely to break when dst changes.)
Could you remove the trailing `)` from the comment?

2018-03-02 16:10 UTC, elfenars commented
Done :D

2018-03-03 21:44 UTC, merged

2018-03-03 21:44 UTC, jeroenj commented
Thanks! 🎉

2018-03-03 21:51 UTC, jeroenj commented
I've released v0.7.0 includin these changes. Thanks a lot again! 👏